package com.only;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-04-19T10:59:56.429+08:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://only.com/", name = "HelloWord")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWord {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCatsByUser", targetNamespace = "http://only.com/", className = "com.only.GetCatsByUser")
    @WebMethod
    @ResponseWrapper(localName = "getCatsByUserResponse", targetNamespace = "http://only.com/", className = "com.only.GetCatsByUserResponse")
    public java.util.List<Cat> getCatsByUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllCats", targetNamespace = "http://only.com/", className = "com.only.GetAllCats")
    @WebMethod
    @ResponseWrapper(localName = "getAllCatsResponse", targetNamespace = "http://only.com/", className = "com.only.GetAllCatsResponse")
    public StringCat getAllCats();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "saHi", targetNamespace = "http://only.com/", className = "com.only.SaHi")
    @WebMethod
    @ResponseWrapper(localName = "saHiResponse", targetNamespace = "http://only.com/", className = "com.only.SaHiResponse")
    public String saHi(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
